apiVersion: v1
kind: Service
metadata:
  name: stepforms-app-service
  labels:
    tier: backend
spec:
  selector:
    app: stepforms-app-container
    tier: backend
  ports:
    - protocol: TCP
      port: 9000
