apiVersion: apps/v1
kind: Deployment
metadata:
  name: stepforms-app
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stepforms-app-container
      tier: backend
  template:
    metadata:
      labels:
        app: stepforms-app-container
        tier: backend
    spec:
      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: stepforms-app-pvc
      containers:
        - name: stepforms-app-container
          image: sweiba/stepforms-example:v2
          env:
            - name: DB_DATABASE
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: database
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: db-secrets
                  key: password
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: "/var/www"
              name: storage
