apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: db
    spec:
      containers:
      - env:
        - name: MYSQL_DATABASE
        - name: MYSQL_PASSWORD
        - name: MYSQL_ROOT_PASSWORD
        - name: MYSQL_USER
        image: mysql:8
        name: stepforms-db
        resources: {}
        tty: true
      restartPolicy: Always
  selector:
    matchLabels:
      io.kompose.service: db
status: {}
