version: "3.7"
services:
  db:
    container_name: stepforms-db
    image: mysql:8
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./var/docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_ROOT_PASSWORD: secret
    tty: true

  stepforms-app:
    container_name: stepforms-api
    build:
      context: docker
      dockerfile: php/Dockerfile
    volumes:
      - .:/var/www
      - ./docker/php/default.ini:/usr/local/etc/php/conf.d/default.ini
      - ./docker/php/opcache.ini:/usr/local/etc/php/conf.d/opcache.ini
      - /var/www/var
      - /var/www/.git
    depends_on:
      - db

  stepforms-nginx:
    image: nginx
    volumes:
      - .:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - stepforms-app
    ports:
    - 80:80
