apiVersion: apps/v1
kind: Deployment
metadata:
  name: stepforms-nginx
  labels:
    tier: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: stepforms-nginx
      tier: backend
  template:
    metadata:
      labels:
        app: stepforms-nginx
        tier: backend
    spec:
      volumes:
        - name: config
          configMap:
            name: stepforms-nginx-config
            items:
              - key: config
                path: default.conf
        - name: stepforms-shared
          emptyDir: {}
      containers:
        - name: nginx
          image: nginx
          ports:
            - containerPort: 80
          volumeMounts:
            - mountPath: "/var/www"
              name: stepforms-shared
            - name: config
              mountPath: /etc/nginx/conf.d
