apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: stepforms-nginx
  name: stepforms-nginx
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: stepforms-nginx
    spec:
      containers:
        - image: nginx
          name: stepforms-nginx
          ports:
            - containerPort: 80
          resources: {}
      restartPolicy: Always
  selector:
    matchLabels:
      io.kompose.service: stepforms-nginx
status: {}
