apiVersion: v1
kind: Service
metadata:
  labels:
    app: stepforms-nginx
    tier: backend
  name: stepforms-nginx
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: stepforms-nginx
status:
  loadBalancer: {}
