apiVersion: apps/v1
kind: Deployment
metadata:
  name: stepforms-app
  labels:
    tier: backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: stepforms-app-container
      tier: backend
  template:
    metadata:
      labels:
        app: stepforms-app-container
        tier: backend
    spec:
      volumes:
        - name: my-pv-storage
          persistentVolumeClaim:
            claimName: my-pv-claim
      containers:
        - name: stepforms-app-container
          image: sweiba/stepforms-example:v2
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: "/var/www"
              name: my-pv-storage
